### ISSUE TITLE
无法登录到界面

### ISSUE THREAD

**Issue by billy74** [liheji/mihomo-yacd#1]
docker创建好之后，访问管理端口弹出页面，但如何连接呢？输入http://127.0.0.1:9090无法连接，输入http://ip:管理端口/api也无法登录进去。

以上是个人使用反馈，此docker内是否已内置了内核服务？还是要自己在安装后才能使用

**Comment by billy74** [comment]
这个容器只是集成了2个管理界面么？如何完整使用服务端进行对接 或 直接将服务端内置到docker里就更完美了

**Comment by liheji** [comment]
按照以下的代码，访问 http://[IP]:8080 可以直接进入管理端口代理地址是：http://[IP]:7890
```yaml
  mihomo:
    container_name: mihomo
    image: yilee01/mihomo-yacd:latest
    ports:
      - "7890:7890"
      - "8080:8080"
    volumes:
      - ./Container/mihomo:/root/.config/mihomo
    restart: on-failure:3
```

示意图：
![image](https://github.com/user-attachments/assets/9bf19ab9-5cb7-495e-8609-da5900266c52)
